### ISSUE TITLE
Licence & contribution?

### ISSUE THREAD

**Issue by jmfayard** [wayfair-contribs/todomvrxdatabinding#1]
Hello!
I have found your project via the Berlindroid announcment where I am also giving a talk
https://www.meetup.com/fr-FR/berlindroid/events/ktlzcrybccbmc/

I saw some quick improvments I could do to the Gradle configuration, but there is no licence in your repo. Is it open-source at all?

**Comment by kojadin** [comment]
Hey Jean,
We are definitely open to contributions. Sorry, somehow slipped and we
didn't add the licence. It is open-source.
I will try to add the licence today.

**Comment by kojadin** [comment]
I added the LICENSE.
